# Sphinx configuration generated by the Documentation Agent pipeline.
import os
import sys

sys.path.insert(0, os.path.abspath('C:\\Users\\justinwe\\Documents\\training\\ghcp-training\\Day 2-20260821T010859Z-1-001\\Day 2\\Lab Activities\\aug_lab2\\SamplePythonAPI'))

project = 'SamplePythonAPI'
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "alabaster"
