"""Sphinx project scaffolding and build automation (workflow phase 4)."""

from __future__ import annotations

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

CONF_TEMPLATE = '''\
# Sphinx configuration generated by the Documentation Agent pipeline.
import os
import sys

sys.path.insert(0, os.path.abspath({source_path!r}))

project = {project!r}
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]
# ignore-module-all avoids documenting re-exported names twice (package + submodule).
autodoc_default_options = {{
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
    "ignore-module-all": True,
}}
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "alabaster"
'''

INDEX_TEMPLATE = '''\
{project} documentation
{underline}

.. toctree::
   :maxdepth: 2
   :caption: API reference:

   modules
'''


@dataclass
class SphinxResult:
    """Outcome of the Sphinx generation phase."""

    apidoc_ok: bool
    build_ok: bool
    output_dir: Path | None
    message: str


def sphinx_available() -> bool:
    """Return True when the sphinx command-line tools are importable."""
    return shutil.which("sphinx-build") is not None or _module_available("sphinx")


def _module_available(name: str) -> bool:
    import importlib.util

    return importlib.util.find_spec(name) is not None


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )


def ensure_project(docs_dir: Path, source_path: Path, project: str) -> None:
    """Create conf.py and index.rst if they do not already exist."""
    docs_dir.mkdir(parents=True, exist_ok=True)
    conf = docs_dir / "conf.py"
    if not conf.exists():
        rel = source_path.resolve()
        conf.write_text(
            CONF_TEMPLATE.format(source_path=str(rel), project=project),
            encoding="utf-8",
        )
    index = docs_dir / "index.rst"
    if not index.exists():
        title = f"{project} documentation"
        index.write_text(
            INDEX_TEMPLATE.format(project=project, underline="=" * len(title)),
            encoding="utf-8",
        )


def generate(docs_dir: Path, source_path: Path, project: str) -> SphinxResult:
    """Run sphinx-apidoc then sphinx-build; never raises on tool failure."""
    if not sphinx_available():
        return SphinxResult(
            apidoc_ok=False,
            build_ok=False,
            output_dir=None,
            message="Sphinx is not installed; skipped generation.",
        )

    abs_docs = docs_dir.resolve()
    abs_source = source_path.resolve()
    ensure_project(abs_docs, abs_source, project)

    apidoc = _run(
        [sys.executable, "-m", "sphinx.ext.apidoc", "-o", str(abs_docs), str(abs_source), "--force"],
        cwd=abs_docs,
    )
    if apidoc.returncode != 0:
        return SphinxResult(
            apidoc_ok=False,
            build_ok=False,
            output_dir=None,
            message=f"sphinx-apidoc failed:\n{apidoc.stderr.strip()}",
        )

    build_dir = abs_docs / "_build" / "html"
    build = _run(
        [sys.executable, "-m", "sphinx", "-b", "html", str(abs_docs), str(build_dir)],
        cwd=abs_docs,
    )
    if build.returncode != 0:
        return SphinxResult(
            apidoc_ok=True,
            build_ok=False,
            output_dir=None,
            message=f"sphinx-build failed:\n{build.stderr.strip()}",
        )

    return SphinxResult(
        apidoc_ok=True,
        build_ok=True,
        output_dir=build_dir,
        message=f"Documentation generated at {build_dir}",
    )
